VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "helldorado-debian-7-7-amd64"

  config.vm.box_url = "http://awh.helldorado.info/helldorado-debian-7-7-amd64.box"

  config.vm.define :client do |client|
    config.vm.hostname = "cacti-client"
    client.vm.network "private_network", ip: "172.20.20.10"
    client.vm.network "forwarded_port", guest: 161, host: 161
  end

  config.vm.define :server do |server|
    config.vm.hostname = "cacti-server"
    server.vm.network "private_network", ip: "172.20.20.20"
    server.vm.network "forwarded_port", guest: 80, host: 8080
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.sudo = true
    #ansible.verbose = 'vvv'
    ansible.host_key_checking = false
    ansible.groups = {
          "server" => "server",
          "client" => "client",
    }
  end
end
